name: Build Release x64 - Visual Studio Native  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: windows-2022  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
      
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v2  
      
    - name: Setup vcpkg (latest stable)  
      run: |  
        git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg  
        cd C:\vcpkg  
        git checkout 2024.07.12  
        .\bootstrap-vcpkg.bat  
        .\vcpkg integrate install  
      
    - name: Install dependencies  
      run: |  
        C:\vcpkg\vcpkg install boost-asio:x64-windows  
        C:\vcpkg\vcpkg install boost-system:x64-windows  
        C:\vcpkg\vcpkg install boost-filesystem:x64-windows  
        C:\vcpkg\vcpkg install boost-iostreams:x64-windows  
        C:\vcpkg\vcpkg install boost-variant:x64-windows  
        C:\vcpkg\vcpkg install boost-lockfree:x64-windows  
        C:\vcpkg\vcpkg install cryptopp:x64-windows  
        C:\vcpkg\vcpkg install luajit:x64-windows  
        C:\vcpkg\vcpkg install libmariadb:x64-windows  
        C:\vcpkg\vcpkg install pugixml:x64-windows  
        C:\vcpkg\vcpkg install mpir:x64-windows  
      
    - name: Update project for modern toolchain  
      run: |  
        # Atualizar Windows SDK para versão disponível  
        (Get-Content vc14\theforgottenserver.vcxproj) -replace '10\.0\.16299\.0', '10.0' | Set-Content vc14\theforgottenserver.vcxproj  
        # Manter PlatformToolset v142 que já está configurado  
      
    - name: Build Release x64  
      run: |  
        msbuild vc14\theforgottenserver.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0 /p:VcpkgRoot=C:\vcpkg /m  
      
    - name: Collect artifacts  
      run: |  
        mkdir artifacts  
        copy vc14\x64\Release\theforgottenserver-x64.exe artifacts\  
        copy vc14\x64\Release\*.dll artifacts\ 2>$null || echo "No DLLs found"  
      
    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: theforgottenserver-release-x64  
        path: artifacts\*
