name: Build Release x64  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: windows-2022  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
      
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v1  
      
    - name: Cache vcpkg  
      uses: actions/cache@v4  
      with:  
        path: C:\vcpkg\installed  
        key: vcpkg-x64-windows-${{ hashFiles('**/appveyor.yml') }}  
        restore-keys: |  
          vcpkg-x64-windows-  
      
    - name: Setup vcpkg  
      run: |  
        if (!(Test-Path "C:\vcpkg")) {  
          git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg  
          C:\vcpkg\bootstrap-vcpkg.bat  
        }  
        C:\vcpkg\vcpkg integrate install  
      
    - name: Install dependencies with verification  
      run: |  
        C:\vcpkg\vcpkg install boost-asio:x64-windows  
        C:\vcpkg\vcpkg install boost-system:x64-windows  
        C:\vcpkg\vcpkg install boost-filesystem:x64-windows  
        C:\vcpkg\vcpkg install boost-iostreams:x64-windows  
        C:\vcpkg\vcpkg install boost-variant:x64-windows  
        C:\vcpkg\vcpkg install boost-lockfree:x64-windows  
        C:\vcpkg\vcpkg install cryptopp:x64-windows  
        C:\vcpkg\vcpkg install luajit:x64-windows  
        C:\vcpkg\vcpkg install libmariadb:x64-windows  
        C:\vcpkg\vcpkg install pugixml:x64-windows  
        C:\vcpkg\vcpkg install mpir:x64-windows  
          
        # Verificar se os headers foram instalados  
        if (Test-Path "C:\vcpkg\installed\x64-windows\include\boost\asio.hpp") {  
          Write-Host "✓ Boost ASIO headers encontrados"  
        } else {  
          Write-Host "✗ Boost ASIO headers NÃO encontrados"  
          exit 1  
        }  
      
    - name: Build Release x64  
      run: |  
        msbuild vc14\theforgottenserver.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0 /p:VcpkgRoot=C:\vcpkg  
      
    - name: Collect artifacts  
      run: |  
        mkdir artifacts  
        copy vc14\x64\Release\*.exe artifacts\  
        copy vc14\x64\Release\*.dll artifacts\  
      
    - name: Upload Release x64  
      uses: actions/upload-artifact@v4  
      with:  
        name: baiak-thunder-release-x64  
        path: artifacts\*
